In [1]:
import pandas as pd
import numpy as np

In [2]:
# Task 1
#Display the details of the customers whose spending score is greater than 80. Also, display the total count of these customers.

ecommerce_data = np.genfromtxt(r"C:\Users\Jishanth M I\Downloads\DS1_C4_S1_Shopping_Data_Challenge.csv", delimiter=',',skip_header=1)

#Finding the customers with spending score greater than 88 
spending_score= ecommerce_data[ecommerce_data[:, 3]> 80]

# Getting customer details
customer_details= spending_score[:, :3]

#Getting count of customers 
count= customer_details.shape[0]

print("Details of customers with spending score greater than 80:", customer_details) 
print("Count of customers with spending score greater than 80:", count)

Details of customers with spending score greater than 80: [[  2.  21.  15.]
 [  8.  23.  18.]
 [ 12.  35.  19.]
 [ 20.  35.  23.]
 [ 26.  29.  28.]
 [ 30.  23.  29.]
 [ 34.  18.  33.]
 [ 36.  21.  33.]
 [ 42.  24.  38.]
 [124.  39.  69.]
 [128.  40.  71.]
 [136.  29.  73.]
 [142.  32.  75.]
 [144.  32.  76.]
 [146.  28.  77.]
 [150.  34.  78.]
 [152.  39.  78.]
 [156.  27.  78.]
 [162.  29.  79.]
 [164.  31.  81.]
 [168.  33.  86.]
 [174.  36.  87.]
 [176.  30.  88.]
 [180.  35.  93.]
 [182.  32.  97.]
 [184.  29.  98.]
 [186.  30.  99.]
 [190.  36. 103.]
 [194.  38. 113.]
 [200.  30. 137.]]
Count of customers with spending score greater than 80: 30


In [3]:
# Task 2
#Extract and display the data of the customers who are 20 to 24 years of age. Note: This data helps analyze age-related expenditures.

#Finding customers between 20 and 24 years old 
over_20_to_24= ecommerce_data[(ecommerce_data[:, 1] >= 20) & (ecommerce_data[:, 1] <= 24)]

# Getting customer details 
Customer_ID= over_20_to_24[:, 0]

# Getting number of employees 
num_employees= Customer_ID.shape[0]

print("Number of customers between 20 and 24 years old:", num_employees) 
print("Customers between 20 and 24 years old:", Customer_ID)

Number of customers between 20 and 24 years old: 23
Customers between 20 and 24 years old: [  2.   3.   4.   6.   8.  14.  16.  18.  30.  32.  36.  40.  42.  46.
  79.  85.  88.  96. 100. 101. 106. 125. 135.]


In [4]:
# Task 3
#Display the IDs of the customers with the lowest annual income(s) and the highest annual income.


#Finding customers with Lowest and highest annual incomes
lowest_annual_income = ecommerce_data[ecommerce_data[:, 2] == np.min(ecommerce_data[:, 2])] 
highest_annual_income= ecommerce_data[ecommerce_data[:, 2] == np.max(ecommerce_data[:, 2])]

# Getting customer IDs
lowest_annual_income_IDs = lowest_annual_income[:, 0] 
highest_annual_income_IDs= highest_annual_income[:, 0]

print("IDs of customers with the lowest annual income:", lowest_annual_income_IDs) 
print("IDs of customers with the highest annual income:", highest_annual_income_IDs)

IDs of customers with the lowest annual income: [1. 2.]
IDs of customers with the highest annual income: [199. 200.]


In [5]:
# Task 4
#Display the details of the customers who are less than 45 years of age, have an annual income greater than $35K, and have a spending score greater than 75. How many such customers are there in the given data?


customer_details = ecommerce_data[(ecommerce_data[:, 1] < 45) & (ecommerce_data[:, 2]> 35) & (ecommerce_data[:, 3]> 75)]

#Displaying the CustomerIDS
Customer_ID=customer_details[:, 0]

#Count of customer_IDS
count=customer_details.shape[0]

print("IDs of customers based on criteria:", Customer_ID)
print("Number of customers:", count)

IDs of customers based on criteria: [ 42. 124. 126. 128. 136. 142. 144. 146. 150. 152. 154. 156. 158. 162.
 164. 168. 174. 176. 180. 182. 184. 186. 190. 194. 196. 200.]
Number of customers: 26


In [6]:
# Task 5
#During the Christmas season, the company wishes to offer random gift coupons valued between $10 and $50 to allits customers. Add a new column for the gift coupons in the existing data. Display the details of the customers after adding the new column.


import random
#Adding new column for gift coupons
gift_coupons = [random.randint(18, 50) for i in range(len(ecommerce_data))] 
gift_coupons= np.array(gift_coupons).reshape(len(gift_coupons), 1) 
ecommerce_data= np.concatenate((ecommerce_data, gift_coupons), axis=1)

print(ecommerce_data)

[[  1.  19.  15.  39.  44.]
 [  2.  21.  15.  81.  45.]
 [  3.  20.  16.   6.  18.]
 [  4.  23.  16.  77.  32.]
 [  5.  31.  17.  40.  22.]
 [  6.  22.  17.  76.  33.]
 [  7.  35.  18.   6.  38.]
 [  8.  23.  18.  94.  23.]
 [  9.  64.  19.   3.  48.]
 [ 10.  30.  19.  72.  41.]
 [ 11.  67.  19.  14.  43.]
 [ 12.  35.  19.  99.  31.]
 [ 13.  58.  20.  15.  42.]
 [ 14.  24.  20.  77.  27.]
 [ 15.  37.  20.  13.  33.]
 [ 16.  22.  20.  79.  32.]
 [ 17.  35.  21.  35.  27.]
 [ 18.  20.  21.  66.  26.]
 [ 19.  52.  23.  29.  47.]
 [ 20.  35.  23.  98.  46.]
 [ 21.  35.  24.  35.  50.]
 [ 22.  25.  24.  73.  36.]
 [ 23.  46.  25.   5.  26.]
 [ 24.  31.  25.  73.  30.]
 [ 25.  54.  28.  14.  34.]
 [ 26.  29.  28.  82.  41.]
 [ 27.  45.  28.  32.  41.]
 [ 28.  35.  28.  61.  48.]
 [ 29.  40.  29.  31.  21.]
 [ 30.  23.  29.  87.  35.]
 [ 31.  60.  30.   4.  43.]
 [ 32.  21.  30.  73.  29.]
 [ 33.  53.  33.   4.  21.]
 [ 34.  18.  33.  92.  39.]
 [ 35.  49.  33.  14.  47.]
 [ 36.  21.  33.  81